### ISSUE TITLE
Add the screenshot from the game

### ISSUE THREAD

**Issue by evgeniy-baba** [katekrasnova/GoPandaGame#1]
To understand what is the game you need to add a screenshot

**Comment by katekrasnova** [comment]
![4_iphone](https://cloud.githubusercontent.com/assets/13893190/20346566/dfbb0946-ac0d-11e6-8960-c87638d49451.png)
![3_iphone](https://cloud.githubusercontent.com/assets/13893190/20346569/e52bd108-ac0d-11e6-8cad-cc28edb394c6.png)
![2_iphone](https://cloud.githubusercontent.com/assets/13893190/20346576/ecf8529e-ac0d-11e6-8d30-2f8e205a6702.png)
![1 iphone](https://cloud.githubusercontent.com/assets/13893190/20346583/f38a7650-ac0d-11e6-9a61-22a4a25722bd.png)

**Comment by katekrasnova** [comment]
Done

**Comment by evgeniy-baba** [comment]
Screenshots of big size and high resolution, you can reduce the size and resolution and optimize for the web? Then the page will be loaded faster

**Comment by katekrasnova** [comment]
Done

**Comment by evgeniy-baba** [comment]
Col :)
